OPENAI_API_KEY = "sk-vPw08kOHKyLlU6Fn64D0Dc055179413f89CbF73b485f6d1c"
OPENAI_MODEL = "gpt-4"
BASE_URL = "https://api.gpt.ge/v1/"

NEO4J_URI = "bolt://52.87.191.213:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "temperatures-attribute-flickers"